### ISSUE TITLE
Contribution

### ISSUE THREAD

**Issue by rejahn** [FelipeGaleao/olho-no-combustivel#1]
Hello, may I contribute to your project?

**Comment by FelipeGaleao** [comment]
Hi @rejahn,

I'm so happy to hear from you!

Yes, you can contribute to this project. We are still organizing our features and roadmap, but we will need help scraping information about gas stations and fuel prices in Brazil, as well as displaying the information on a web platform (both on the frontend and backend). Initially, we will be working with FastAPI on the backend, and React on the frontend.

If you are interested, let me know here!

Best regards!

**Comment by rejahn** [comment]
I think working with you guys on the API would be nice!
